### ISSUE TITLE
"Open Project" command not working

### ISSUE THREAD

**Issue by HAuzian** [randy3k/ProjectManager#102]
First of all, many thanks for this awesome package, can't work without it!

Since today I started getting issues while using the "Project Manager: Open Project" command, either via shortcut or via command palette. Nothing appears on screen when calling the command.

Checking the Sublime console, I get this error:

`
Traceback (most recent call last):
  File "/home/<my-username>/.config/sublime-text-3/Installed Packages/ProjectManager.sublime-package/project_manager.py", line 665, in <lambda>
  File "/opt/sublime_text/sublime.py", line 463, in show_quick_panel
    flags, selected_index)
TypeError: String required
`

I did a clean install of Sublime Text 3.2.2, removing all my previous settings and project files, and installing Package Control and Project Manager from scratch, and I get the same error. Creating new projects works fine, though.

Manually installing a previous version of `ProjectManager.sublime-package` inside my "Installed packages" folder fixed the issue, so apparently there's something different with the current version 0.7.20 that is causing the issue.

Many thanks in advance :pray: 

### Environment

```text
ProjectManager:

    version: 0.7.20
    installed via Package Control: True

Sublime Text:
    channel: stable
    version: 3211
    platform: Linux
    portable: no
    architecture: x64
```

**Comment by randy3k** [comment]
Should be fixed in 9fb3a46 and 0.7.21 is on the way.

**Comment by randy3k** [comment]
By the way, sorry for the incontinence.

**Comment by HAuzian** [comment]
Thanks for the quick response!

**Comment by HAuzian** [comment]
Just downloaded 0.7.21 from Package Control and it's working perfect. Issue closed, thank you!
