### ISSUE TITLE
Project can't fetch folders

### ISSUE THREAD

**Issue by wakkermedia** [randy3k/ProjectManager#44]
Hi there,

I have installed SublimeText 3 with Project-Manager on my new MacBook. When I create a new project and add folders to it, the project doesn't open this folders the next time I open the project. I have 2 other Mac's which doesn't seem to have this problem. I've re-installed Sublime Text several times now, but still no luck. 

Maybe you can shed some light at this problem?

Surely hope so! 

With kind regards, 

Douwe Hoogeveen

**Comment by randy3k** [comment]
Are there any error messages in the sublime text console (invoke via " ctrl +` ") ?

**Comment by kumiao** [comment]
i have the same problem

**Comment by kumiao** [comment]
![image](http://hbimg.b0.upaiyun.com/a0d4d328e2a6c7730dd54b91c0dab870113b8ff125ee0-VARGUb_fw658)

**Comment by randy3k** [comment]
@kumiao 
I rediscovered your messages after almost half a year. Does the problem still persist? I guess it is because you didn't add any folders to the project.

**Comment by randy3k** [comment]
closed due to inactivity.
