### ISSUE TITLE
Creation of new project fails

### ISSUE THREAD

**Issue by kiddick** [randy3k/ProjectManager#46]
I have existing project with no folders and with several `untitled` (tmp) files.
So I am trying to add new project and it fails:

``` python
Traceback (most recent call last):
  File "pm in ..\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package", line 234, in show_input_panel
KeyError: 'folders'
```

**Comment by randy3k** [comment]
You must have some folders added to Sublime to set up a project. Simply drag and drop a folder to Sublime.

**Comment by kiddick** [comment]
Yep, it resolves that issue.
But is there any way how to automatically handle that by package?

**Comment by randy3k** [comment]
Actually, I cannot find a way to reproduce the errors...

**Comment by randy3k** [comment]
closed due to inactivity.
