### ISSUE TITLE
projects_path issue

### ISSUE THREAD

**Issue by jpagarcia** [randy3k/ProjectManager#55]
Problem: I have a custom project path in **project_path** in Project Manager's user settings but it is not used. It saves and checks projects in **C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\User\Projects**. 

I tried restarting ST3 after changing the path in the user settings. Also tried reinstalling project manager. Deleted the Projects folder and my project manager settings in the said path. But all of these didn't work.

**Comment by randy3k** [comment]
I apologize for the bug. It has been fixed in version v0.7.1. If you are using Package Control, you may need to wait for half an hour or so.

**Comment by jpagarcia** [comment]
It was really frustrating not being able to use my folder. I also tried reinstalling ST3 for the sake of Project Manager. I just can't use ST3 without your Project Manager anymore. Thanks for the quick reply and fix! One of the best, if not the best, plugin for ST3! Hope you keep up the support. Thanks!

**Comment by randy3k** [comment]
Thanks for being interested in this package. I have no plan to not support this as long as I am still using Sublime Text.
