### ISSUE TITLE
Feature Request: Copy Project

### ISSUE THREAD

**Issue by jpagarcia** [randy3k/ProjectManager#57]
@randy3k Is it possible to add a feature where I could make a copy of a project?
I tried manually copying the sublime-project and sublime-workspace files and changing config in the sublime-project files, but I wasn't able to get the result that I wanted.

**Comment by randy3k** [comment]
how about just saving the current project again by `Project Manager: Add Project`?

**Comment by jpagarcia** [comment]
that worked! thanks thanks! not that intuitive but what's important is that it works. Thanks!
