### ISSUE TITLE
[Feature Request] Deleting unwanted workspaces from Sublime.sublime-session file

### ISSUE THREAD

**Issue by Kristinita** [randy3k/ProjectManager#58]
### Description

I use `/E/Sublime Text 3/Data/Packages/User/Проект.sublime-workspace` workspace, others workspaces not needs for me, I want remove unnecessary workspaces form my `Sublime.sublime-session` file. My workspaces:

![My workspaces](http://i.imgur.com/4byMuwF.png)

Part of my `Session.sublme-session` file.

```
"workspaces":
    {
        "recent_workspaces":
        [
            "/E/Sublime Text 3/Data/Packages/User/Проект.sublime-workspace",
            "/e/Sublime Text 3/Data/Packages/User/Проект.sublime-workspace",
            "/e/Sublime Text 3 Portable For Tests/Data/Packages/User/Проект.sublime-workspace",
            "/D/Sublime Text 3/Data/Packages/User/Проект.sublime-workspace"
        ]
    }
```
### Request

I want to be able to remove the workspaces in Project Manager. Now I need remove workspace [manually](http://petrkout.com/other/remove-projects-from-sublime-text-switch-project-window/). `Project Manager: Clean Recent Project` and `Project Manager: Remove Dead Project` not helped me.

Yes, I can remove all workspaces, if I press `Project`→ `Open Recent` → `Clear Items`. But I don't need remove all workspaces.

Thanks.

**Comment by randy3k** [comment]
Is it really that important to keep an item? You can always clear all and then open the project that you need.

**Comment by Kristinita** [comment]
> Is it really that important to keep an item? You can always clear all and then open the project that you need.

Yes, if user have much more than one active projects. 

![Many projects](http://i.stack.imgur.com/iZaJ1.png)

Thanks.

**Comment by randy3k** [comment]
This is the build it Project Manager...but this package :-/

**Comment by Karl-EdwardFPJeanMehu** [comment]
Having this feature really alleviate the stress of removing them manually. It is after all a "project manager".

**Comment by randy3k** [comment]
I personally never use the "Open Recent" option since the Projects are already sorted by recency.

**Comment by randy3k** [comment]
close by e9bcacb
