### ISSUE TITLE
"Open project in new window" doesn't work in Windows

### ISSUE THREAD

**Issue by DrStrangepork** [randy3k/ProjectManager#59]
I am trying to mimic this behavior which works in OSX:

```
{
    "keys": ["super+ctrl+o"],
    "command": "project_manager", "args": {"action": "new"}
}
```

I have tried several iterations of "keys" and tried adding the settings to my _User\Default (Windows).sublime-keymap_ file in addition to/instead of the _User\project_manager.sublime-settings_
file, but still nothing.

**Comment by randy3k** [comment]
You should put the following to `Default (Windows).sublime-keymap` 

```
{
    "keys": ["ctrl+alt+o"],
    "command": "project_manager", "args": {"action": "new"}
}
```

`super` key is not defined in Windows

**Comment by DrStrangepork** [comment]
I understand that. I am using the code you just posted in my `User\Default (Windows).sublime-keymap` file, and it doesn't work. The `Default\Default (Windows).sublime-keymap` file cannot be edited directly in Windows.

**Comment by randy3k** [comment]
You are right, the keybind should go to `User\Default (Windows).sublime-keymap`.

Is there any error message from the Sublime console?

**Comment by SitiSchu** [comment]
> { "keys": ["ctrl+alt+o"], "command": "project_manager", "args": {"action": "new"}}

Works flawless on Windows 10

**Comment by DrStrangepork** [comment]
Closing, I no longer use SB3.
