### ISSUE TITLE
Append Project is not working

### ISSUE THREAD

**Issue by howar31** [randy3k/ProjectManager#60]
I can't find usage instruction about Append Project in README.md.  I tried using Append Project but nothing happened.  The opened tabs were not append to project I selected.  When I reopen the project, the appended tabs were lost.

How exactly this function works?  Is it currently broken now?

**Comment by randy3k** [comment]
It is still working. Is there any error message in the console?  Perhaps you have misunderstood the usage of `Append Project`. It is used for adding folders from other projects to the sidebar.

**Comment by howar31** [comment]
Oh!  The sidebars did works!

I misunderstood the usage and sorry for bothering. :sweat_smile:
