### ISSUE TITLE
Prevent project duplication

### ISSUE THREAD

**Issue by stfoo** [randy3k/ProjectManager#61]
Hi!

Maybe I am wrong, but in some of previous versions `Open project in new window` have worked differently. It wouldn't open new window if there already is one opened with that project, it would just switch to that window.

Now it opens new window in any case and I end up with a lot of windows. 

Is there a way to prevent project duplication?

**Comment by randy3k** [comment]
It should close the original window and open a new one. What OS are you using? Are your project folder a symlinked directory?

**Comment by stfoo** [comment]
macOS 10.12, 
it's regular folder

**Comment by randy3k** [comment]
Could you open the project and report the followings from the console?

```
window.project_file_name()
```
and
```
from ProjectManager import pm
pm.Manager(window).project_file_name("<YOUR PROJECT NAME>")
```

**Comment by stfoo** [comment]
```
>>> window.project_file_name()
'/Users/stfoo/Library/Application Support/Sublime Text 3/Packages/User/Projects/book-ui.sublime-project'

>>> pm.Manager(window).project_file_name("book-ui")
'/Users/stfoo/Library/Application Support/Sublime Text 3/Packages/User/Projects/book-ui.sublime-project'
```

**Comment by stfoo** [comment]
Wait. I noticed that it happens not always. For that project it worked just as you said. But for one that was on background Manager opened a new window. Output there:

```
>>> window.project_file_name()

```
it's empty

```
>>> pm.Manager(window).project_file_name("book-typography")
'/Users/stfoo/Library/Application Support/Sublime Text 3/Packages/User/Projects/book-typography.sublime-project'
```

**Comment by randy3k** [comment]
So the one in the background was not opened by Project Manager?

**Comment by stfoo** [comment]
Ha. Yeah, it was restored by Sublime, when I reopened it. Is there a way to get around it?

**Comment by randy3k** [comment]
I guess you could just close that window, and use PM to open the project again.
Sublime should be able to pick up the project when you reopen Sublime.

**Comment by randy3k** [comment]
PM always opens `sublime-project` file so `window.project_file_name()` should not be empty for projects maintained by PM. It was mostly because you opened the directory directly instead of the `sublime-project` file or using PM.

**Comment by stfoo** [comment]
Yeah, I guess I could accidentely open that projects from a terminal
Thank you for your time and thank you for that project! :)

**Comment by randy3k** [comment]
Please reopen this if the problem persists.
