### ISSUE TITLE
Add new project does nothing

### ISSUE THREAD

**Issue by tlarkworthy** [randy3k/ProjectManager#66]
I am running Project Manager on ST3 (Windows 10 x64), and the "Add New Project" feature does nothing for me. The only way I can add projects is by importing or manually moving the *.sublime-project files.

**Comment by randy3k** [comment]
Is there any message in the console? You need to open a directory before "Add a new Project".

**Comment by tlarkworthy** [comment]
Nevermind, I didn't notice the "new project name" bar at the bottom of the screen! Possibly because of my theme.
