### ISSUE TITLE
new project files created but path is wrong - "path": "."

### ISSUE THREAD

**Issue by v3nt** [randy3k/ProjectManager#67]
This means it always opens the /packages/User/Projects folder and not the actual project location.

 
## Expected behaviour
Should add correct  path to project file.

...

## Actual behaviour
adds the relative path - "path": "."
 
### Environment

```text
ProjectManager:

    version: 0.7.2
    installed via Package Control: True

Sublime Text:

    channel: stable
    version: 3126
    platform: windows
    portable: yes
    architecture: x64
```

**Comment by randy3k** [comment]
? How did you add the project file?

**Comment by v3nt** [comment]
Most were created over time in Sublime text. Some created using your package.

I have 50+ projects so any project management packages ideally would fix path (or other) issues.

**Comment by randy3k** [comment]
A newly created project should use the already showing folders. You must be dragging some existing projects to the `Projects` without fixing the path.

**Comment by v3nt** [comment]
no - no dragging. When the manager is disabled the sublime-project files work.

**Comment by randy3k** [comment]
I am confused then, how did you actually add the projects to Project Manager.

**Comment by v3nt** [comment]
when the project was open i used 'add project'. Is that the correct way to add projects that already exist?

**Comment by randy3k** [comment]
It is not the documented way to do so. User might expect it should work except that this not working, will improve it soon.

**Comment by randy3k** [comment]
The latest code should have improved this use case. Please report again if it doesn't work for you.
