### ISSUE TITLE
Open Project not working

### ISSUE THREAD

**Issue by yonishin** [randy3k/ProjectManager#68]
# Open Project not working

## Summary
I try Open Project, but app window close, and nothing show. Project don't open.

### Environment

```text
ProjectManager:

    version: 0.7.7
    installed via Package Control: True

Sublime Text:

    channel: dev build
    version: 3142
    platform: mac os Sierra (10.12.6)
```

**Comment by randy3k** [comment]
Did you add any projects in the first place?

**Comment by yonishin** [comment]
1. Open Sublime Text window.
2. Project > Project Manager > Add New Project.
3. After that App window close.
4. Reopen the program window.
5. Go to  Project > Project Manager > Open Project.
6. And again, the program window disappears.

**Comment by randy3k** [comment]
um, a new window should be reopen after step 2 with same folder of the closed window (if there are any). Could you try again but drag a folder to the sidebar first?

**Comment by yonishin** [comment]
If I add folder then it's OK. But, if I want first create project, or I have only files (without folder) then Project Manager not working (app windows disappear).

**Comment by randy3k** [comment]
It works for me with empty sidebar..not sure why it doesn't work for you.

**Comment by randy3k** [comment]
Oh, I see why. It is because of the sublime text settings `close_windows_when_empty`. I have this option off.

**Comment by randy3k** [comment]
should be fixed in 0.7.8. It should appear in Package Control soon.

**Comment by randy3k** [comment]
Ai...still not completely fixed. The best solution for now is to turn off `close_windows_when_empty`.

**Comment by yonishin** [comment]
Yes. For now I use close_windows_when_empty: false. And Project Manager works good. Thanks!
