### ISSUE TITLE
OS-centric Project Manager files?

### ISSUE THREAD

**Issue by naknode** [randy3k/ProjectManager#70]
# Short and descriptive example bug report title

## Summary

I use Sublime Text 3 heavily both on my personal and work projects. I have the settings synced via Dropbox because I do the same kind of work in both projects.

Anyway,  something cool that popped up would be to have OS-centric project mananager files like the keybinders that have (OSX) and (Windows) in their files. I say this because obviously, Windows 10 and unix-like systems have different file structure. So when I bring up projects on my Mac, I get the Windows projects and vice-versa which is not fun.

### Environment

```text
ProjectManager:

    version: 0.7.2
    installed via Package Control: True

Sublime Text:

    channel: stable
    version: 3126
    platform: windows
    portable: yes
    architecture: x64
```

**Comment by randy3k** [comment]
May be you can try using the `use_local_projects_dir` option?

**Comment by naknode** [comment]
Hi @randy3k ,

I just tried that. It did not work. Nothing, to my knowledge, changed.

**Comment by randy3k** [comment]
You may need to classify the projects into the different Project Folders. There should be two folders,
`Project - {YOUR WINDOWS MACHINE NAME}` and `Project - {YOUR LINUX MACHINE NAME}`.

**Comment by naknode** [comment]
I can confirm that seemed to have work. I must have missed those folders the first time.

I can now view projects filtered by their OS (computer name, really).

**Comment by randy3k** [comment]
There is another (manual but more flexible) solution if you are using the just release version 0.7.11.

First, classify the Windows/Linux projects into different folders. Then tell dropbox how the folders should be synced. (i.e., do not create and sync `Project - Windows` to Linux and vice versa).

Then specify both folders in the setting `projects_path`. If the `Project - Windows` doesn't exist on Linux, Project Manager will ignore the path to the `Project - Windows` on Linux. On the other hand, ignore `Project - Linux` on Windows respectively.
