### ISSUE TITLE
Undo/redo lost when navigating to a new project and returning to original project

### ISSUE THREAD

**Issue by codequistador** [randy3k/ProjectManager#71]
# Short and descriptive example bug report title

Undo/redo lost when navigating to a new project and returning to original project

## Summary

Say I have two projects. A and B. I am currently in project A making changes. I go to project B for inspiration on project A. I return to project A. I am not able to undo changes made in project A after going from A -> B -> A

```text
ProjectManager:

    version: 0.7.12
    installed via Package Control: True

Sublime Text:

    channel: stable
    version: 3143
    platform: Mac
```

**Comment by randy3k** [comment]
It is kind of expected. The undo stack is not persistent over reopening of the project.
File a feature request to Sublime Text if you really need this.

Alternatively, you can map a keybind for opening project in a new window: https://github.com/randy3k/ProjectManager#faq
