### ISSUE TITLE
Project Manager opens nothing and makes ST to loose system references

### ISSUE THREAD

**Issue by Nemesis19** [randy3k/ProjectManager#75]
Dear developer,

I use intensively Project Manager, but lately I'm experiencing a weird behaviour. I'm trying to explain it but it's not really easy to reproduce, actually I don't know under which circumstances it does happen.

I'm using MacOS 10.13.3.

Description of the problem:
- I open Sublime Text 3 (bug happens since latest 3-4 dev versions, let's say from 3156, I'm now on 3160)
- I open a project in new window calling the key shortcut ( with args: new) or I open the project in the current window
- I close the project with Super+W by closing all the tabs, ST stays open and when I click it on the dock I open a new blank window (sidebar for open files is closed, I'm showing only the folder tree)
- sometimes the ProjectManager keys, menu command and palette command are working, sometimes are not, leaving no trace in ST Console
- if I open from ST a .sublime-project file, ST opens it perfectly

The only information that I can add at this point is that sometimes the bug happens when I leave idle ST for some minutes...but I don't really know if it's a useful information...

After all this procedure, the very weirdest thing is that ST loses system references to file handlers. As example, let's assume I assign via Finder to open all JSON files always with ST. Once the ProjectManager bug happens, that system reference gets lost and that JSON gets opened with another app.

Is there a way I can help you track down this issue?

Many thanks,
regards

**Comment by randy3k** [comment]
That’s weird. It’s never happened to me. Anyway, a better way to close a project is to do `super + shift + w` (if it is not what you were using).

**Comment by Nemesis19** [comment]
I never use the full key-combo because I'm using "close_windows_when_empty": true in ST settings, that does the same thing of super + shift + w when you close the last tab/file.

I forgot to mention that sometimes the problem happens when a project is open, I press the keys to open a new project with "args: new" as per your docs...and ST does simply nothing. I need to close it and reopen to make Project Manager to work as expected.

Do you need to make the plugin compatible with the latest dev version? maybe there is something incompatible...

**Comment by randy3k** [comment]
I am using the dev builds...never experience anything like that

**Comment by Nemesis19** [comment]
Is there anything I can check that is not the ST Console (already checked)...any way I can put the plugin in debug mode...or ST in debug mode.

Thanks

**Comment by randy3k** [comment]
try running `sublime.log_commands(True)` in the sublime console. It will log every command executed. You might be able to find some clues from there.

**Comment by Nemesis19** [comment]
```
command: drag_select {"event": {"button": 1, "x": 802.91015625, "y": 344.703125}}
command: project_manager {"action": "switch"}
Updated
Updated
command: project_manager {"action": "new"}
Updated
using gpu buffer for window
Updated
command: drag_select {"event": {"button": 1, "x": 882.85546875, "y": 458.7109375}}
command: drag_select {"event": {"button": 1, "x": 839.984375, "y": 249.359375}}
command: project_manager {"action": "switch"}
Updated
Updated
command: close
command: drag_select {"event": {"button": 1, "x": 886.140625, "y": 163.9921875}}
command: project_manager {"action": "switch"}
Updated
Updated
command: project_manager {"action": "new"}
Updated
Updated
command: project_manager {"action": "new"}
Updated
Updated
command: drag_select {"event": {"button": 1, "x": 13.4375, "y": 375.03125}}
```

it seems nothing unusual but still projects won't open, randomly...I need to restart sublime to make it work again when it gets stuck

**Comment by Nemesis19** [comment]
After a bit testing, it seems there is some incompatibility with PackageSync plugin for Sublime Text. I disabled it for a while and the issue with Project Manager seems gone, I then decided to uninstall PackageSync and sync my Sublime Text folder under MacOS with MacDropAny and Dropbox.

Please keep open this thread for a week or two, I'll then close it after further testing.
