### ISSUE TITLE
When will thsi be the default Project Manager for Sublime text

### ISSUE THREAD

**Issue by selwynorren** [randy3k/ProjectManager#82]
No Bug at all. Just wanted to thank you for the most go-to plugin for Sublime text. Any chance the devs will make your plugin the defacto way all projects are managed in Sublime Text?

Thank you for a fantastic plugin

**Comment by randy3k** [comment]
I don’t think I will happen at all as Sublime Text already has one.

**Comment by selwynorren** [comment]
Such a pity as yours works so much better.

Take Care
