### ISSUE TITLE
Switching between projects repeatedly causes Sublime 3 to crash

### ISSUE THREAD

**Issue by fy2** [randy3k/ProjectManager#88]
# Sublime 3 crashes when switching between projects
### Environment

```text
ProjectManager:


    installed via Package Control: True

Sublime Text:

    channel: stable
    version: 3207
    platform: MacOS Mojave 10.14.4
    portable: yes
    architecture: x64
```

**Comment by BarbzYHOOL** [comment]
never noticed that personally

**Comment by Zsedo** [comment]
Happening to me since yesterday as well.

**Comment by yangkennyk** [comment]
This is happening to me too since the new sublime updates

**Comment by randy3k** [comment]
Could those experience the issue report your platform and sublime version?

**Comment by nadieenespecial** [comment]
Same here

```
ProjectManager: installed via Package Control: True
Sublime Text:
    channel: stable
    version: 3207
    platform: Debian 9.8 
    architecture: x86_64
```

**Comment by einar-johan** [comment]
I'm experiencing this as well, got the exact versions as @fy2 , both on my mac at work, and my  mac at home.

Build 3207 on MacOS Mojave 10.14.4

**Comment by stephenll** [comment]
I am seeing it as well.  

I've been trying to figure out the cause... For me it seems to happen with only one project.  If I remove that project I can switch all I want and it doesn't seem to crash.  Add it back in, switch to it and crash.  So I removed that project.  Restarted Sublime.  Created a new project that has the parent directory of the original project as the project.  Before I had `~/SourceControl/Exams/ExamABC`,  and that crashed.  Now I have `~/SourceControl/Exams/` and that seems to work.

    ProjectManager: installed via Package Control: True
    Sublime Text:
        Build: 3208
        MacOS Mojave 10.14.4

**Comment by randy3k** [comment]
I am also on macOS 10.14.4 and ST 3208, but I haven't seen any issues so far.

**Comment by stephenll** [comment]
I tried to replicate the error again. I added the crashing project back in to the project manager.  At first I didn't experience a crash.  Rapidly flipping between projects at first was fine.  After a few more rapid flipping between the project that was crashing and one I haven't had a problem with, on the last switch to the crashing project, sublime had a short delay and then crash.

**Comment by jrdnbwmn** [comment]
Mine is crashing as well, same as other above:

```
ProjectManager:

    Installed via Package Control: True

Sublime Text:

    channel: stable
    version: 3207
    platform: MacOS Mojave 10.14.4
    portable: yes
    architecture: x64
```

**Comment by BarbzYHOOL** [comment]
I don't have this on ubuntu 14.04 so maybe it's mac OS related

What if it's related to a package you all have in common?

**Comment by yangkennyk** [comment]
I'm seeing an issue where sometimes when I launch sublime and it opens to a project. switching to some projects will insta crash sublime. I have to switch to a different project so that the one that opens with sublime on launch is different. then I can switch to the project that was crashing. it seems to be inconsistent though.

**Comment by yangkennyk** [comment]
was anyone able to figure out a fix? I've just reverted back to 3170 for the time being.

**Comment by fy2** [comment]
> was anyone able to figure out a fix? I've just reverted back to 3170 for the time being.

I have stopped using this plugin, and resorted to Sublime's native project manager.

**Comment by jcagarcia** [comment]
The same problem here

**Comment by tsantzi** [comment]
Same here, Debian 9 x64 w/ Cinnamon 3.2.7. Issue appeared after upgrading to 3207. Always involves loading up a project file.

**Comment by andywarren** [comment]
Happening constantly to me. 

Sublime v3.2.1, Build 3207
ProjectManager v0.7.15

**Comment by roblav96** [comment]
Possible solution PR #91 opens the workspace file instead of the project file.

@f2y @yangkennyk @jcagarcia @tsantzi @andywarren

**Comment by randy3k** [comment]
I have pulled @roblav96 PR and made a new release. Sorry for the wait.

**Comment by randy3k** [comment]
0.7.17 is now on its way. Hopefully, it will fix this long lasting issue.
