### ISSUE TITLE
Support for extended path / regex path in folder_exclude_patterns

### ISSUE THREAD

**Issue by mrsean2k** [randy3k/ProjectManager#93]
## Summary
I routinely exclude - for example - `node_modules` using `folder_exclude_patterns` but I'd like to be able to specify either a specific path to the folder in question, or a regex containing that path.

For example, given

````
  +project-root-directory
    -node_modules
    +src
      -node_modules
      +components
        -main
        -node_modules
      -build
````
I'd like to be able to exclude `project-root-directory/node_modules` but allow the others to be included.

### Environment

```text
ProjectManager:

    version: 0.7.19
    installed via Package Control: True
    
Sublime Text
    version: 3211
    platform: Linux
```

**Comment by randy3k** [comment]
it is more a general sublime text question, I don’t know if  it is achievable.

**Comment by mrsean2k** [comment]
Thanks - it looks like a long-standing issue with the way these paths are processed in ST3 with possible fixes in ST4. Ah well.
