### ISSUE TITLE
Specific syntax for .js files in the project

### ISSUE THREAD

**Issue by zigi05** [randy3k/ProjectManager#99]
I need to use JSX syntax highlighting for `.js` files in one of my projects. Sublime's _**View > Syntax > Open all with current extension as > JSX**_ will make all `.js` files to use JSX syntax highlighting across all projects, whereas I need it only in one specific project. Is there a way to set JSX syntax highlighting for `.js` files for one specific project using the ProjectManager, or maybe there's another way to achieve that?

I'm aware of the separate package allowing to do that, but I'd rather not use any additional packages.

**Comment by rchl** [comment]
That's not really a job for ProjectManager IMO and it doesn't let you do that now.

Assigning JSX syntax to all `.js` will most likely do no harm to plain JS files. They should still look and feel the same as with JS syntax as JSX syntax just extends the JS syntax.

And of course, there is the https://facelessuser.github.io/ApplySyntax/ package which is probably what you referred to.
